name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PUBLICPATH: "/vocabulary-trainer"

      - name: Deploy on GH-Pages
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'Umfi'
          reponame: 'vocabulary-trainer'
          token: ${{ secrets.GITHUB_TOKEN }} 